Add release command

diff --git a/agileflow b/agileflow
--- a/agileflow
+++ b/agileflow
@@ -95,10 +95,6 @@ install_command() {
                 echo ".gitlab-ci.yml already contains AgileFlow configuration. No changes were made."
             fi
             
-
-            
-
-
             ;;
         GitHub)
             # Display instructions for GitHub similar to GitLab's instructions but using base64 < "$TEMP_DIR/agileflow-deploy-key" instead of cat for the private key since GitHub doesn't support file type CD/CI variables
@@ -124,6 +120,63 @@ install_command() {
 
     rm -rf "$TEMP_DIR"
     exit 0
+}
+
+release_command() {
+    # git fetch all the branches from the remotes
+    git fetch --all
+
+    MAJOR_RELEASE=false
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --major)
+                MAJOR_RELEASE=true
+                shift
+                ;;
+            *)
+                usage
+                ;;
+        esac
+    done
+    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+    if [[ "$BRANCH_NAME" == "HEAD" || -z "$BRANCH_NAME" ]]; then
+        if [[ -n "$CI_COMMIT_REF_NAME" ]]; then
+            BRANCH_NAME="$CI_COMMIT_REF_NAME"
+        elif [[ -n "$GITHUB_REF_NAME" ]]; then
+            BRANCH_NAME="$GITHUB_REF_NAME"
+        elif [[ -n "$GITHUB_REF" ]]; then
+            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+        else
+            echo "[ERROR] Unable to determine branch name."
+            exit 1
+        fi
+    fi
+
+    if [[ ! "$BRANCH_NAME" =~ ^release/[0-9]+\.[0-9]+$ ]]; then
+        echo "[ERROR] Branch name '$BRANCH_NAME' does not match 'release/MAJOR.MINOR'."
+        exit 1
+    fi
+
+    VERSION="${BRANCH_NAME#*/}"
+    MAJOR=$(echo "$VERSION" | cut -d. -f1)
+    MINOR=$(echo "$VERSION" | cut -d. -f2)
+
+    if $MAJOR_RELEASE; then
+        MAJOR=$((MAJOR + 1))
+        MINOR=0
+    else
+        MINOR=$((MINOR + 1))
+    fi
+
+    NEXT_RELEASE="release/$MAJOR.$MINOR"
+
+    if git show-ref --verify --quiet "refs/heads/$NEXT_RELEASE"; then
+        echo "[ERROR] Branch '$NEXT_RELEASE' already exists."
+        exit 1
+    fi
+
+    git checkout -b "$NEXT_RELEASE"
+    echo "[INFO] Next release branch: $NEXT_RELEASE"
 }
 
 # Function to handle 'tag' command
@@ -226,6 +279,9 @@ shift
 case "$COMMAND" in
     install)
         install_command "$@"
+        ;;
+    release)
+        release_command "$@"
         ;;
     tag)
         tag_command "$@"
