Externalize get_branch_name function

diff --git a/agileflow b/agileflow
--- a/agileflow
+++ b/agileflow
@@ -11,6 +11,22 @@ usage() {
     exit 1
 }
 
+get_branch_name() {
+    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+    if [[ "$BRANCH_NAME" == "HEAD" || -z "$BRANCH_NAME" ]]; then
+        if [[ -n "$CI_COMMIT_REF_NAME" ]]; then
+            BRANCH_NAME="$CI_COMMIT_REF_NAME"
+        elif [[ -n "$GITHUB_REF_NAME" ]]; then
+            BRANCH_NAME="$GITHUB_REF_NAME"
+        elif [[ -n "$GITHUB_REF" ]]; then
+            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+        else
+            echo "[ERROR] Unable to determine branch name."
+            exit 1
+        fi
+    fi
+}
+
 # Function to handle 'install' command
 install_command() {
     CI_CD_ENGINE=""
@@ -141,24 +157,7 @@ release_command() {
         shift
     done
 
-    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-    if [[ "$BRANCH_NAME" == "HEAD" || -z "$BRANCH_NAME" ]]; then
-        if [[ -n "$CI_COMMIT_REF_NAME" ]]; then
-            BRANCH_NAME="$CI_COMMIT_REF_NAME"
-        elif [[ -n "$GITHUB_REF_NAME" ]]; then
-            BRANCH_NAME="$GITHUB_REF_NAME"
-        elif [[ -n "$GITHUB_REF" ]]; then
-            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
-        else
-            echo "[ERROR] Unable to determine branch name."
-            exit 1
-        fi
-    fi
-
-    if [[ ! "$BRANCH_NAME" =~ ^release/[0-9]+\.[0-9]+$ ]]; then
-        echo "[ERROR] Branch name '$BRANCH_NAME' does not match 'release/MAJOR.MINOR'."
-        exit 1
-    fi
+    get_branch_name
 
     VERSION="${BRANCH_NAME#*/}"
     MAJOR=$(echo "$VERSION" | cut -d. -f1)
@@ -168,13 +167,16 @@ release_command() {
         MAJOR=$((MAJOR + 1))
         MINOR=0
     else
+        if ! [[ "$MAJOR" =~ ^[0-9]+$ ]]; then
+            MAJOR=0
+        fi
         MINOR=$((MINOR + 1))
     fi
 
     NEXT_RELEASE="release/$MAJOR.$MINOR"
 
     if git show-ref --verify --quiet "refs/heads/$NEXT_RELEASE"; then
-        echo "[ERROR] Branch '$NEXT_RELEASE' already exists."
+        echo "[ERROR] Release branch '$NEXT_RELEASE' already exists."
         exit 1
     fi
 
@@ -235,20 +237,7 @@ tag_command() {
         echo "[INFO] Converted remote URL to SSH: $SSH_URL"
     fi
 
-    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-    if [[ "$BRANCH_NAME" == "HEAD" || -z "$BRANCH_NAME" ]]; then
-        if [[ -n "$CI_COMMIT_REF_NAME" ]]; then
-            BRANCH_NAME="$CI_COMMIT_REF_NAME"
-        elif [[ -n "$GITHUB_REF_NAME" ]]; then
-            BRANCH_NAME="$GITHUB_REF_NAME"
-        elif [[ -n "$GITHUB_REF" ]]; then
-            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
-        else
-            echo "[ERROR] Unable to determine branch name."
-            rm -rf "$TEMP_DIR"
-            exit 1
-        fi
-    fi
+    get_branch_name
 
     if [[ ! "$BRANCH_NAME" =~ ^(r|release)/[0-9]+\.[0-9]+$ ]]; then
         echo "[ERROR] Branch name '$BRANCH_NAME' does not match 'r/X.Y' or 'release/X.Y'."
